export const FIND_ALL_UNIT = "FIND_ALL_UNIT"
export const FIND_ALL_UNIT_SUCCESS = "FIND_ALL_UNIT_SUCCESS"
export const FIND_ALL_UNIT_FAILURE = "FIND_ALL_UNIT_FAILURE"

export const FIND_UNIT_BY_ID = "FIND_UNIT_BY_ID"
export const FIND_UNIT_BY_ID_SUCCESS = "FIND_UNIT_BY_ID_SUCCESS"
export const FIND_UNIT_BY_ID_FAILURE = "FIND_UNIT_BY_ID_FAILURE"

export const REMOVE_UNIT_BY_ID = "REMOVE_UNIT_BY_ID"
export const REMOVE_UNIT_BY_ID_SUCCESS = "REMOVE_UNIT_BY_ID_SUCCESS"
export const REMOVE_UNIT_BY_ID_FAILURE = "REMOVE_UNIT_BY_ID_FAILURE"

export const UPDATE_UNIT = "UPDATE_UNIT"
export const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS"
export const UPDATE_UNIT_FAILURE = "UPDATE_UNIT_FAILURE"